block.block.ridiculously_responsive_social_share_buttons:
  expected_config: {  }
  update_actions:
    add:
      visibility:
        node_type:
          bundles:
            discussion: discussion
eu_cookie_compliance.settings:
  expected_config:
    mobile_popup_info:
      format: basic_html
      value: ''
    popup_agreed:
      format: restricted_html
    popup_info:
      format: restricted_html
    withdraw_message:
      format: restricted_html
      value: '<h2>This site uses cookies to offer you a better browsing experience. </h2><p>You have given your consent for us to set cookies.</p>'
  update_actions:
    change:
      mobile_popup_info:
        format: plain_text
        value: '<h2>We use cookies on this site to enhance your user experience</h2><p>By tapping the Accept button, you agree to us doing so.</p>'
      popup_agreed:
        format: plain_text
      popup_info:
        format: plain_text
      withdraw_message:
        format: plain_text
        value: '<h2>We use cookies on this site to enhance your user experience</h2><p>You have given your consent for us to set cookies.</p>'
message.template.comment_created:
  expected_config: { }
  update_actions:
    delete:
      text:
    change:
      text:
        -
          value: "<div class=\"message--text\"><a href=\"[message:author:url:absolute]\">[message:author:display-name]</a>&nbsp;commented on <a href=\"[message:field_node_reference:entity:url]\">[message:trimmed-node-title]:</a> <a href=\"[message:comment-url]\">[message:trimmed-comment]</a></div>\r\n"
          format: full_html
        -
          value: "<p>[site:name] New comment!</p>\r\n"
          format: basic_html
        -
          value: "<p>[message:author:display-name] commented on [message:trimmed-node-title]:[message:trimmed-comment]</p>\r\n"
          format: basic_html
