__global_actions:
  import_configs:
    - layout_builder_styles.style.card
  install_modules:
    - bootstrap4_modal
block.block.ridiculously_responsive_social_share_buttons:
  expected_config: {  }
  update_actions:
    add:
      visibility:
        node_type:
          bundles:
            discussion: discussion
eu_cookie_compliance.settings:
  expected_config:
    mobile_popup_info:
      format: basic_html
      value: ''
    popup_agreed:
      format: restricted_html
    popup_info:
      format: restricted_html
    withdraw_message:
      format: restricted_html
      value: '<h2>This site uses cookies to offer you a better browsing experience. </h2><p>You have given your consent for us to set cookies.</p>'
  update_actions:
    change:
      mobile_popup_info:
        format: plain_text
        value: '<h2>We use cookies on this site to enhance your user experience</h2><p>By tapping the Accept button, you agree to us doing so.</p>'
      popup_agreed:
        format: plain_text
      popup_info:
        format: plain_text
      withdraw_message:
        format: plain_text
        value: '<h2>We use cookies on this site to enhance your user experience</h2><p>You have given your consent for us to set cookies.</p>'
block.block.mobile_footer_block:
  expected_config: {  }
  update_actions:
    add:
      visibility:
        node_type:
          bundles:
            discussion: discussion
block.block.ridiculously_responsive_social_share_buttons_footer:
  expected_config: {  }
  update_actions:
    add:
      visibility:
        node_type:
          bundles:
            discussion: discussion
core.entity_form_display.node.article.default:
  expected_config:
    content:
      field_images:
        settings:
          entity_browser: openideal_images_browser
          field_widget_edit: true
          field_widget_remove: true
          field_widget_replace: true
          open: false
          preview_image_style: thumbnail
          selection_mode: selection_append
          view_mode: default
        type: entity_browser_file
  update_actions:
    delete:
      content:
        field_images:
          settings:
            entity_browser: openideal_images_browser
            field_widget_edit: true
            field_widget_remove: true
            field_widget_replace: true
            open: false
            selection_mode: selection_append
            view_mode: default
    change:
      content:
        field_images:
          settings:
            crop_list:
              - image
            crop_preview_image_style: original
            crop_types_required: {  }
            preview_image_style: front_page_teaser_large
            progress_indicator: throbber
            show_crop_area: false
            show_default_crop: true
            warn_multiple_usages: false
          type: image_widget_crop
