core.entity_view_display.message.challenge_schedule.default:
  expected_config: {  }
  update_actions:
    add:
      content:
        field_node_reference:
          settings:
            limit: 0
            offset: 0
      hidden:
        partial_3: true
core.entity_view_display.message.challenge_schedule.mail_body:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        partial_3: true
core.entity_view_display.message.challenge_schedule.mail_subject:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        partial_3: true
core.entity_view_display.message.create_challenge.default:
  expected_config: {  }
  update_actions:
    add:
      content:
        field_node_reference:
          settings:
            limit: 0
            offset: 0
      hidden:
        partial_3: true
core.entity_view_display.message.create_challenge.mail_body:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        partial_3: true
core.entity_view_display.message.create_challenge.mail_subject:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        partial_3: true
core.entity_view_display.message.node_created.default:
  expected_config: {  }
  update_actions:
    add:
      content:
        field_node_reference:
          settings:
            limit: 0
            offset: 0
      hidden:
        partial_3: true
core.entity_view_display.message.node_created.mail_body:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        partial_3: true
core.entity_view_display.message.node_created.mail_subject:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        partial_3: true
message.template.challenge_schedule:
  expected_config: { }
  update_actions:
    add:
      dependencies:
        config:
          - filter.format.message
      text:
        -
          format: message
          value: "{\r\n    \"text\": \"Challenge [message:field_node_reference:entity:title] is now @challenge_status.\",\r\n    \"blocks\": [\r\n    \t{\r\n    \t\t\"type\": \"section\",\r\n    \t\t\"text\": {\r\n    \t\t\t\"type\": \"mrkdwn\",\r\n    \t\t\t\"text\": \"Challenge <[message:field_node_reference:entity:url]|[message:field_node_reference:entity:title]> is now @challenge_status.\"\r\n    \t\t}\r\n    \t}\r\n   ]\r\n}"
message.template.create_challenge:
  expected_config: { }
  update_actions:
    add:
      dependencies:
        config:
          - filter.format.message
      text:
        -
          format: message
          value: "{\r\n    \"text\": \"New challenge: [message:field_node_reference:entity:title].\",\r\n    \"blocks\": [\r\n    \t{\r\n    \t\t\"type\": \"section\",\r\n    \t\t\"text\": {\r\n    \t\t\t\"type\": \"mrkdwn\",\r\n    \t\t\t\"text\": \"New challenge:<[message:field_node_reference:entity:url]|[message:field_node_reference:entity:title]>\"\r\n    \t\t}\r\n    \t}\r\n   ]\r\n}"
message.template.node_created:
  expected_config: {  }
  update_actions:
    add:
      dependencies:
        config:
          - filter.format.message
      text:
        -
          format: message
          value: "{\r\n    \"text\": \"New [message:field_node_reference:entity:content-type]: [message:field_node_reference:entity:title].\",\r\n    \"blocks\": [\r\n    \t{\r\n    \t\t\"type\": \"section\",\r\n    \t\t\"text\": {\r\n    \t\t\t\"type\": \"mrkdwn\",\r\n    \t\t\t\"text\": \"New [message:field_node_reference:entity:content-type] <[message:field_node_reference:entity:url]|[message:field_node_reference:entity:title]>\"\r\n    \t\t}\r\n    \t}\r\n   ]\r\n}"
